### ISSUE TITLE
Configuring mail on gitlab-docker

### ISSUE THREAD

**Issue by eelcocramer** [crashsystems/gitlab-docker#15]
Hi,

I recently installed gitlab using your Docker image and it rocks!

The only thing not working for me is that gitlab does not send emails (or I do not receive them).

Now I was hoping that if I created a smtp configuration in `config/initializers/smtp_settings.rb` it would be picked up by gitlab but unfortunately this does not seem to be the case.

Anyone got this sorted?
Should email be working out-of-the-container?

Thanks,
Eelco

**Comment by eelcocramer** [comment]
I fixed this by adding `production.rb` and `smtp_settings.rb` to the config folder and adding the appropriate copy commands to the startup script.

**Comment by matejkramny** [comment]
Was this fixed? I never get mail from the docker instance..
