### ISSUE TITLE
Reusing SSH port

### ISSUE THREAD

**Issue by doubleyou** [crashsystems/gitlab-docker#2]
If you have sshd running on the host system (which is mostly the case), the container doesn't start.

Of course, port 22 can be forwarded to some other port number, like 9022, but in that case you'll have to use different names to SSH to that machine, either for host system SSH login or for git.

Any thoughts how to fix this?

**Comment by crashsystems** [comment]
That's a good question. I did this because I'm not aware of a way to use SSH as a git transport over a nonstandard port. So for this, I just edited the host's ssh config to run on port 23.

**Comment by nls44** [comment]
https://github.com/crashsystems/gitlab-docker/pull/6 fixes this. This allows you to have Git urls as such: 

ssh://git@localhost:45678/root/testproject.git

This also doesn't require you to edit the ~/.ssh/config either.
