### ISSUE TITLE
Step 3 in readme.md in case of pulled image

### ISSUE THREAD

**Issue by lodagro** [crashsystems/gitlab-docker#3]
Intead of building gitlab i pulled _crashsystems/gitlab_. This implied that in step 3 of readme.md the command to create a new container instance is

```
docker run -d -v /path/to/gitlab-docker:/srv/gitlab crashsystems/gitlab
```

**Comment by crashsystems** [comment]
Good point. I just updated the readme to have both versions of the run command.

https://github.com/crashsystems/gitlab-docker/commit/4919c97e70285e02bb61326c9e79602d11d2b1a0
